### ISSUE TITLE
Setting "away" status crashes daemon

### ISSUE THREAD

**Issue by rozzin** [moparisthebest/telepaatti#2]
e.g.:
<pre>
May 25 01:42:27 feep xmpp-ircd[23658]: got ircline: AWAY :thinking
May 25 01:42:27 feep xmpp-ircd[23658]: DEBUG: socket       sent  <presence to="foxtrotgps@chatrooms.hackerposse.com/rozzin-irc1" from="03jrwov642fqmgth82m3@irc.hackerposse.com" id="2">
May 25 01:42:27 feep xmpp-ircd[23658]:   <show xmlns="jabber:client">away</show>
May 25 01:42:27 feep xmpp-ircd[23658]:   <status xmlns="jabber:client">thinking</status>
May 25 01:42:27 feep xmpp-ircd[23658]:   </presence>
May 25 01:42:27 feep xmpp-ircd[23658]: DEBUG: socket       sent  <presence from="03jrwov642fqmgth82m3@irc.hackerposse.com" id="3">
May 25 01:42:27 feep xmpp-ircd[23658]:   <show xmlns="jabber:client">away</show>
May 25 01:42:27 feep xmpp-ircd[23658]:   <status xmlns="jabber:client">thinking</status>
May 25 01:42:27 feep xmpp-ircd[23658]:   </presence>
May 25 01:42:27 feep xmpp-ircd[23658]: :irc.hackerposse.com 306 rozzin-irc1 :You have been marked as being away
May 25 01:42:27 feep xmpp-ircd[23658]: DEBUG: socket       got   <presence to='03jrwov642fqmgth82m3@irc.hackerposse.com' from='foxtrotgps@chatrooms.hackerposse.com/rozzin-irc1' id='2'>
May 25 01:42:27 feep xmpp-ircd[23658]:   <x xmlns='http://jabber.org/protocol/muc#user'>
May 25 01:42:27 feep xmpp-ircd[23658]:   <item jid='03jrwov642fqmgth82m3@irc.hackerposse.com' role='participant' affiliation='none'/>
May 25 01:42:27 feep xmpp-ircd[23658]:   <status code='110'/>
May 25 01:42:27 feep xmpp-ircd[23658]:   </x>
May 25 01:42:27 feep xmpp-ircd[23658]:   <show>away</show>
May 25 01:42:27 feep xmpp-ircd[23658]:   <status>thinking</status>
May 25 01:42:27 feep xmpp-ircd[23658]:   </presence>
May 25 01:42:27 feep xmpp-ircd[23658]: DEBUG: dispatcher   ok    Got jabber:component:accept/presence stanza
May 25 01:42:27 feep xmpp-ircd[23658]: DEBUG: dispatcher   ok    Dispatching presence stanza with type-> props->[u'http://jabber.org/protocol/muc#user', u'jabber:component:accept'] id->2
May 25 01:42:27 feep xmpp-ircd[23658]: in presenceHandler
May 25 01:42:27 feep xmpp-ircd[23658]: jid 03jrwov642fqmgth82m3@irc.hackerposse.com, clients: {'03jrwov642fqmgth82m3@irc.hackerposse.com': <ClientThread(Thread-2, started 139751547291392)>}
May 25 01:42:27 feep xmpp-ircd[23658]: not unavailable
May 25 01:42:27 feep xmpp-ircd[23658]: DEBUG: socket       got   <stream:error>
May 25 01:42:27 feep xmpp-ircd[23658]:   <improper-addressing xmlns='urn:ietf:params:xml:ns:xmpp-streams'/>
May 25 01:42:27 feep xmpp-ircd[23658]:   <text xml:lang='en' xmlns='urn:ietf:params:xml:ns:xmpp-streams'>Missing &apos;to&apos; attribute</text>
May 25 01:42:27 feep xmpp-ircd[23658]:   </stream:error>
May 25 01:42:27 feep xmpp-ircd[23658]: DEBUG: dispatcher   ok    Got http://etherx.jabber.org/streams/error stanza
May 25 01:42:27 feep xmpp-ircd[23658]: DEBUG: dispatcher   ok    Dispatching error stanza with type-> props->[u'urn:ietf:params:xml:ns:xmpp-streams'] id->None
May 25 01:42:27 feep xmpp-ircd[23658]: Exception in thread Thread-1:
May 25 01:42:27 feep xmpp-ircd[23658]: Traceback (most recent call last):
May 25 01:42:27 feep xmpp-ircd[23658]:   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
May 25 01:42:27 feep xmpp-ircd[23658]:     self.run()
May 25 01:42:27 feep xmpp-ircd[23658]:   File "/srv/xmpp-ircd/xmpp-ircd.py", line 59, in run
May 25 01:42:27 feep xmpp-ircd[23658]:     while self.client.Process(1) and self.connected:
May 25 01:42:27 feep xmpp-ircd[23658]:   File "/usr/lib/python2.7/dist-packages/xmpp/dispatcher.py", line 303, in dispatch
May 25 01:42:27 feep xmpp-ircd[23658]:     handler['func'](session,stanza)
May 25 01:42:27 feep xmpp-ircd[23658]:   File "/usr/lib/python2.7/dist-packages/xmpp/dispatcher.py", line 215, in streamErrorHandler
May 25 01:42:27 feep xmpp-ircd[23658]:     raise exc((name,text))
May 25 01:42:27 feep xmpp-ircd[23658]: ImproperAddressing: (u'improper-addressing', u"Missing 'to' attribute")
May 25 01:42:34 feep xmpp-ircd[23658]: got ircline: AWAY
May 25 01:42:34 feep xmpp-ircd[23658]: DEBUG: socket       sent  <presence to="foxtrotgps@chatrooms.hackerposse.com/rozzin-irc1" from="03jrwov642fqmgth82m3@irc.hackerposse.com" id="4">
May 25 01:42:34 feep xmpp-ircd[23658]:   <status xmlns="jabber:client">
May 25 01:42:34 feep xmpp-ircd[23658]:   </status>
May 25 01:42:34 feep xmpp-ircd[23658]:   </presence>
May 25 01:42:34 feep xmpp-ircd[23658]: DEBUG: socket       error Socket error while sending data
May 25 01:42:34 feep xmpp-ircd[23658]: Traceback (most recent call last):
May 25 01:42:34 feep xmpp-ircd[23658]:   File "/usr/lib/python2.7/dist-packages/xmpp/transports.py", line 180, in send
May 25 01:42:34 feep xmpp-ircd[23658]:     self._send(raw_data)
May 25 01:42:34 feep xmpp-ircd[23658]:   File "/usr/lib/python2.7/socket.py", line 228, in meth
May 25 01:42:34 feep xmpp-ircd[23658]:     return getattr(self._sock,name)(*args)
May 25 01:42:34 feep xmpp-ircd[23658]: error: [Errno 32] Broken pipe
May 25 01:42:34 feep xmpp-ircd[23658]: DEBUG: component    stop  Disconnect detected
May 25 01:42:34 feep xmpp-ircd[23658]: DEBUG: socket       error Socket operation failed
May 25 01:42:34 feep xmpp-ircd[23658]: Traceback (most recent call last):
May 25 01:42:34 feep xmpp-ircd[23658]:   File "/usr/lib/python2.7/dist-packages/xmpp/transports.py", line 180, in send
May 25 01:42:34 feep xmpp-ircd[23658]:     self._send(raw_data)
May 25 01:42:34 feep xmpp-ircd[23658]:   File "/usr/lib/python2.7/socket.py", line 228, in meth
May 25 01:42:34 feep xmpp-ircd[23658]:     return getattr(self._sock,name)(*args)
May 25 01:42:34 feep xmpp-ircd[23658]: error: [Errno 32] Broken pipe
May 25 01:42:34 feep xmpp-ircd[23658]: Exception in thread Thread-2:
May 25 01:42:34 feep xmpp-ircd[23658]: Traceback (most recent call last):
May 25 01:42:34 feep xmpp-ircd[23658]:   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
May 25 01:42:34 feep xmpp-ircd[23658]:     self.run()
May 25 01:42:34 feep xmpp-ircd[23658]:   File "/srv/xmpp-ircd/xmpp-ircd.py", line 814, in run
May 25 01:42:34 feep xmpp-ircd[23658]:     self.commandHandler(line)
May 25 01:42:34 feep xmpp-ircd[23658]:   File "/srv/xmpp-ircd/xmpp-ircd.py", line 1543, in commandHandler
May 25 01:42:34 feep xmpp-ircd[23658]:     self.xmppCommandSTATUS(show, status)
May 25 01:42:34 feep xmpp-ircd[23658]:   File "/srv/xmpp-ircd/xmpp-ircd.py", line 665, in xmppCommandSTATUS
May 25 01:42:34 feep xmpp-ircd[23658]:     self.sendToXMPP(p)
May 25 01:42:34 feep xmpp-ircd[23658]:   File "/srv/xmpp-ircd/xmpp-ircd.py", line 253, in sendToXMPP
May 25 01:42:34 feep xmpp-ircd[23658]:     self.component.send(msg)
May 25 01:42:34 feep xmpp-ircd[23658]:   File "/srv/xmpp-ircd/xmpp-ircd.py", line 1678, in send
May 25 01:42:34 feep xmpp-ircd[23658]:     self.client.send(msg)
May 25 01:42:34 feep xmpp-ircd[23658]:   File "/usr/lib/python2.7/dist-packages/xmpp/dispatcher.py", line 367, in send
May 25 01:42:34 feep xmpp-ircd[23658]:     self._owner_send(stanza)
May 25 01:42:34 feep xmpp-ircd[23658]:   File "/usr/lib/python2.7/dist-packages/xmpp/transports.py", line 188, in send
May 25 01:42:34 feep xmpp-ircd[23658]:     self._owner.disconnected()
May 25 01:42:34 feep xmpp-ircd[23658]:   File "/usr/lib/python2.7/dist-packages/xmpp/client.py", line 129, in disconnected
May 25 01:42:34 feep xmpp-ircd[23658]:     for i in self.disconnect_handlers: i()
May 25 01:42:34 feep xmpp-ircd[23658]:   File "/usr/lib/python2.7/dist-packages/xmpp/client.py", line 137, in DisconnectHandler
May 25 01:42:34 feep xmpp-ircd[23658]:     raise IOError('Disconnected from server.')
May 25 01:42:34 feep xmpp-ircd[23658]: IOError: Disconnected from server.
</pre>

Running with ejabberd; not sure if maybe this doesn't happen with Prosody or other servers.

**Comment by rozzin** [comment]
For the time being, I guess just decaying the "AWAY" command to a no-op is OK, until this can actually be debugged....

I'm not even sure I've actually ever even seen anyone use that on IRC, so maybe this feature doesn't even matter that much?

**Comment by bqv** [comment]
it is used, on irc, it should be translated to xa, in my opinion
